---
- name: Ensure wanted VS Code extensions are installed
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ lookup('env', 'USER') }}"
        visual_studio_code_extensions:
          - 4ops.terraform
          - bradlc.vscode-tailwindcss
          - castanhocorreia.alphabetize
          - cfcluan.project-scopes
          - dbaeumer.vscode-eslint
          - eamodio.gitlens
          - esbenp.prettier-vscode
          - firsttris.vscode-jest-runner
          - formulahendry.auto-close-tag
          - formulahendry.auto-rename-tag
          - GitHub.copilot
          - GitHub.copilot-chat
          - github.vscode-github-actions
          - hediet.vscode-drawio
          - kddejong.vscode-cfn-lint
          - kisstkondoros.vscode-codemetrics
          - MariusAlchimavicius.json-to-ts
          - mechatroner.rainbow-csv
          - miguelsolorio.fluent-icons
          - ms-playwright.playwright
          - ms-vscode.makefile-tools
          - ryanluker.vscode-coverage-gutters
          - shardulm94.trailing-spaces
          - streetsidesoftware.code-spell-checker
          - GitHub.github-vscode-theme
